import { learningGradebookRepository } from "../repositories/learning-gradebook.repository";
export const learningGradebookService={
 listCategories:(organizationId:string)=>learningGradebookRepository.listCategories(organizationId),
 listTerms:(organizationId:string)=>learningGradebookRepository.listTerms(organizationId),
 listEntries:(input:Parameters<typeof learningGradebookRepository.listEntries>[0])=>learningGradebookRepository.listEntries(input),
 listTermGrades:(input:Parameters<typeof learningGradebookRepository.listTermGrades>[0])=>learningGradebookRepository.listTermGrades(input),
 listTopics:(topicIds:string[])=>learningGradebookRepository.listTopics(topicIds),
 createCategory:(input:Parameters<typeof learningGradebookRepository.createCategory>[0])=>learningGradebookRepository.createCategory(input),
 updateCategory:(input:Parameters<typeof learningGradebookRepository.updateCategory>[0])=>learningGradebookRepository.updateCategory(input),
 createEntry:(input:Parameters<typeof learningGradebookRepository.createEntry>[0])=>learningGradebookRepository.createEntry(input),
 updateManualEntry:(input:Parameters<typeof learningGradebookRepository.updateManualEntry>[0])=>learningGradebookRepository.updateManualEntry(input),
 setEntryIncludedInGrade:(entryId:string,includedInGrade:boolean,updatedBy:string)=>learningGradebookRepository.setEntryIncludedInGrade(entryId,includedInGrade,updatedBy),
 deleteManualEntry:(entryId:string,reason?:string)=>learningGradebookRepository.deleteManualEntry(entryId,reason),
 reopenTermGrade:(input:Parameters<typeof learningGradebookRepository.reopenTermGrade>[0])=>learningGradebookRepository.reopenTermGrade(input),
 overrideTermGrade:(input:Parameters<typeof learningGradebookRepository.overrideTermGrade>[0])=>learningGradebookRepository.overrideTermGrade(input),
 listAudit:(input:Parameters<typeof learningGradebookRepository.listAudit>[0])=>learningGradebookRepository.listAudit(input),
 bulkImportEntries:(input:Parameters<typeof learningGradebookRepository.bulkImportEntries>[0])=>learningGradebookRepository.bulkImportEntries(input),
 createManualEntry:(input:Parameters<typeof learningGradebookRepository.createManualEntry>[0])=>learningGradebookRepository.createManualEntry(input),
 calculateTermGrade:(input:Parameters<typeof learningGradebookRepository.calculateTermGrade>[0])=>learningGradebookRepository.calculateTermGrade(input),
 finalizeTermGrade:(input:Parameters<typeof learningGradebookRepository.finalizeTermGrade>[0])=>learningGradebookRepository.finalizeTermGrade(input),
};