import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, BookOpen, Save } from "lucide-react";
import type { FormEvent, ReactNode } from "react";
import { useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/core/auth";
import { learningContentService } from "@/features/learning-content";
import { learningTeacherService } from "@/features/learning-teacher";
import type { LearningContentType } from "@/features/learning-content";

const contentTypes: LearningContentType[]=["lesson","explanation","reading","listening","speaking","writing","worksheet","video","audio","interactive","reference","other"];
export default function TeacherContentCreatePage(){
 const{user}=useAuth();const navigate=useNavigate();const[curriculumId,setCurriculumId]=useState("");const[gradeLevelId,setGradeLevelId]=useState("");const[subjectId,setSubjectId]=useState("");const[skillId,setSkillId]=useState("");const[topicId,setTopicId]=useState("");const[objectiveId,setObjectiveId]=useState("");const[title,setTitle]=useState("");const[code,setCode]=useState("");const[contentType,setContentType]=useState<LearningContentType>("lesson");const[languageCode,setLanguageCode]=useState("en");const[body,setBody]=useState("");const[changeSummary,setChangeSummary]=useState("");const[error,setError]=useState("");const[saving,setSaving]=useState(false);
 const classes=useQuery({queryKey:["learning","teacher-classes",user?.id],queryFn:()=>learningTeacherService.listTeacherClasses(user!.id),enabled:Boolean(user?.id)});const organizationId=classes.data?.[0]?.membership.organizationId;
 const curricula=useQuery({queryKey:["learning","curricula"],queryFn:()=>learningContentService.listCurricula(),enabled:Boolean(user?.id)});const gradeLevels=useQuery({queryKey:["learning","grade-levels",curriculumId],queryFn:()=>learningContentService.listGradeLevels(curriculumId),enabled:Boolean(curriculumId)});const subjects=useQuery({queryKey:["learning","subjects",curriculumId],queryFn:()=>learningContentService.listSubjects(curriculumId),enabled:Boolean(curriculumId)});const skills=useQuery({queryKey:["learning","skills",subjectId],queryFn:()=>learningContentService.listSkills(subjectId),enabled:Boolean(subjectId)});const topics=useQuery({queryKey:["learning","topics",skillId],queryFn:()=>learningContentService.listTopics(skillId),enabled:Boolean(skillId)});const aligns=useQuery({queryKey:["learning","objective-alignments",curriculumId,gradeLevelId],queryFn:()=>learningContentService.listAlignments(undefined,curriculumId,gradeLevelId),enabled:Boolean(curriculumId&&gradeLevelId)});const objectives=useQuery({queryKey:["learning","objectives",topicId],queryFn:()=>learningContentService.listObjectives(topicId),enabled:Boolean(topicId)});const existing=useQuery({queryKey:["learning","teacher-content-library",organizationId],queryFn:()=>learningContentService.listContent(organizationId),enabled:Boolean(organizationId)});
 const aligned=useMemo(()=>new Set((aligns.data??[]).map(x=>x.objectiveId)),[aligns.data]);const selected=objectives.data?.find(x=>x.id===objectiveId);
 const resetCurriculum=(v:string)=>{setCurriculumId(v);setGradeLevelId("");setSubjectId("");setSkillId("");setTopicId("");setObjectiveId("")};const resetSubject=(v:string)=>{setSubjectId(v);setSkillId("");setTopicId("");setObjectiveId("")};
 async function saveDraft(e:FormEvent){e.preventDefault();setError("");if(!user?.id||!organizationId){setError("Your teacher organization could not be determined.");return}if(!curriculumId||!gradeLevelId||!subjectId||!skillId||!topicId||!objectiveId||!title.trim()||!code.trim()||!body.trim()){setError("Complete the subject, skill, topic, objective, title, code, and content body.");return}if(!aligned.has(objectiveId)){setError("Select a learning objective aligned to the chosen curriculum and grade level.");return}const normalized=code.trim().toUpperCase();if((existing.data??[]).some(x=>x.code.toUpperCase()===normalized)){setError("That content code already exists in this organization. Use a different code.");return}setSaving(true);try{const content=await learningContentService.createContent({organizationId,code:normalized,title:title.trim(),contentType,languageCode,createdBy:user.id});await learningContentService.createVersion({contentItemId:content.id,versionNo:1,body:{sections:[{type:"text",title:"Content",body:body.trim()}]},changeSummary:changeSummary.trim()||"Initial draft",createdBy:user.id});await learningContentService.addObjective({contentItemId:content.id,objectiveId,sequenceNo:1});navigate("/teacher/content",{replace:true})}catch(err){setError(err instanceof Error?err.message:"Could not save the content draft.")}finally{setSaving(false)}}
 if(!user)return <Message text="Sign in to create learning content."/>;if(classes.isPending||curricula.isPending)return <div className="h-96 animate-pulse rounded-2xl bg-slate-200"/>;if(classes.isError||curricula.isError||!organizationId)return <Message text="We could not determine your teacher organization."/>
 return <div className="mx-auto max-w-4xl space-y-6"><header className="flex items-center gap-3"><Link to="/teacher/content" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><ArrowLeft size={19}/></Link><div><div className="flex items-center gap-2 text-sm font-medium text-slate-500"><BookOpen size={18}/>Teacher Content</div><h1 className="mt-1 text-2xl font-bold text-slate-900">Create Content</h1><p className="mt-1 text-sm text-slate-500">Build a reusable learning material and save it as a draft.</p></div></header>
 <form onSubmit={saveDraft} className="space-y-6"><Section number="1" title="Academic alignment" description="Choose the curriculum structure this material belongs to."><Field label="Curriculum"><select value={curriculumId} onChange={e=>resetCurriculum(e.target.value)} className="input w-full" required><option value="">Select curriculum</option>{(curricula.data??[]).map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select></Field><Field label="Grade level"><select value={gradeLevelId} onChange={e=>{setGradeLevelId(e.target.value);setObjectiveId("")}} className="input w-full" required><option value="">Select grade level</option>{(gradeLevels.data??[]).map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select></Field><Field label="Subject"><select value={subjectId} onChange={e=>resetSubject(e.target.value)} className="input w-full" required><option value="">Select subject</option>{(subjects.data??[]).map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select></Field><Field label="Skill"><select value={skillId} onChange={e=>{setSkillId(e.target.value);setTopicId("");setObjectiveId("")}} className="input w-full" required><option value="">Select skill</option>{(skills.data??[]).map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select></Field><Field label="Topic"><select value={topicId} onChange={e=>{setTopicId(e.target.value);setObjectiveId("")}} className="input w-full" required><option value="">Select topic</option>{(topics.data??[]).map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select></Field><Field label="Learning objective"><select value={objectiveId} onChange={e=>setObjectiveId(e.target.value)} className="input w-full" required><option value="">Select learning objective</option>{(objectives.data??[]).filter(x=>aligned.has(x.id)).map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select>{selected?.description&&<p className="mt-2 text-xs text-slate-500">{selected.description}</p>}</Field></Section>
 <Section number="2" title="Content details" description="Give the learning material its identity and format."><Field label="Title"><input value={title} onChange={e=>{setTitle(e.target.value);if(!code)setCode(slugify(e.target.value))}} className="input w-full" required/></Field><Field label="Content code"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} className="input w-full" required/></Field><Field label="Content type"><select value={contentType} onChange={e=>setContentType(e.target.value as LearningContentType)} className="input w-full">{contentTypes.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></Field><Field label="Language"><select value={languageCode} onChange={e=>setLanguageCode(e.target.value)} className="input w-full"><option value="en">English</option><option value="th">Thai</option><option value="sw">Swahili</option></select></Field></Section>
 <Section number="3" title="Content body" description="Write the first draft of the learning material." full><Field label="Learning content"><textarea value={body} onChange={e=>setBody(e.target.value)} className="input min-h-64 w-full resize-y" required/></Field><Field label="Change summary (optional)"><input value={changeSummary} onChange={e=>setChangeSummary(e.target.value)} className="input w-full"/></Field></Section>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}<div className="flex justify-end gap-3"><Link to="/teacher/content" className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold">Cancel</Link><button type="submit" disabled={saving||existing.isPending} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save size={17}/>{saving?"Saving draft...":"Save Draft"}</button></div></form></div>
}
function Section({number,title,description,children,full=false}:{number:string;title:string;description:string;children:ReactNode;full?:boolean}){return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-900 text-sm font-bold text-white">{number}</span><h2 className="text-lg font-semibold text-slate-900">{title}</h2></div><p className="mt-2 text-sm text-slate-500">{description}</p><div className={`mt-5 grid gap-4 ${full?"":"md:grid-cols-2"}`}>{children}</div></section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{label}</span>{children}</label>}
function Message({text}:{text:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-600">{text}</div>}
function slugify(v:string){return v.trim().toUpperCase().replace(/[^A-Z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
function label(v:string){return v.charAt(0).toUpperCase()+v.slice(1)}
