import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Save, Settings, Plus } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useAuth } from "@/core/auth";
import { supabase } from "@/core/infrastructure/supabase/client";
import { learningGradebookService } from "../services/learning-gradebook.service";
import { learningTeacherService } from "@/features/learning-teacher";

type Scale={id:string;organization_id:string;code:string;name:string;status:string};
type Rule={id:string;grade_scale_id:string;min_percentage:number;max_percentage:number;grade:number;label:string;sequence_no:number};

export default function TeacherGradebookSettingsPage(){
 const {user}=useAuth();const{classGroupId=""}=useParams();const qc=useQueryClient();
 const classQ=useQuery({queryKey:["learning","teacher-gradebook-settings-class",user?.id,classGroupId],queryFn:()=>learningTeacherService.getClassOverview(user!.id,classGroupId),enabled:Boolean(user?.id&&classGroupId)});
 const org=classQ.data?.classInfo.membership.organizationId??"";const subjects=classQ.data?.classInfo.subjects??[];const [subjectId,setSubjectId]=useState("");
 const selectedSubjectId=subjectId||subjects[0]?.id||"";
 const cats=useQuery({queryKey:["learning","gradebook-settings-categories",org],queryFn:()=>learningGradebookService.listCategories(org),enabled:Boolean(org)});
 const scales=useQuery({queryKey:["learning","gradebook-settings-scales",org],queryFn:async()=>{const{data,error}=await supabase.from("learning_grade_scales" as never).select("*").eq("organization_id",org).order("name");if(error)throw error;return(data??[]) as unknown as Scale[]},enabled:Boolean(org)});
 const rules=useQuery({queryKey:["learning","gradebook-settings-rules",org],queryFn:async()=>{const ids=(scales.data??[]).map(s=>s.id);if(!ids.length)return[];const{data,error}=await supabase.from("learning_grade_scale_rules" as never).select("*").in("grade_scale_id",ids).order("sequence_no");if(error)throw error;return(data??[]) as unknown as Rule[]},enabled:Boolean(org&&scales.data)});
 const[categoryForm,setCategoryForm]=useState({id:"",code:"",name:"",weight:"1",description:"",status:"active"});
 const[scaleForm,setScaleForm]=useState({code:"",name:""});
 const[method,setMethod]=useState("weighted_percentage");const[scaleId,setScaleId]=useState("");
 const updateCat=useMutation({mutationFn:()=>categoryForm.id?learningGradebookService.updateCategory({id:categoryForm.id,code:categoryForm.code.trim(),name:categoryForm.name.trim(),description:categoryForm.description,defaultWeight:Number(categoryForm.weight),status:categoryForm.status}):learningGradebookService.createCategory({organizationId:org,code:categoryForm.code.trim(),name:categoryForm.name.trim(),description:categoryForm.description,defaultWeight:Number(categoryForm.weight)}),onSuccess:()=>{setCategoryForm({id:"",code:"",name:"",weight:"1",description:"",status:"active"});void qc.invalidateQueries({queryKey:["learning","gradebook-settings-categories"]});void qc.invalidateQueries({queryKey:["learning","gradebook-categories"]})}});
 const createScale=useMutation({mutationFn:async()=>{if(!scaleForm.code.trim()||!scaleForm.name.trim())throw new Error("Scale code and name are required.");const{data,error}=await supabase.from("learning_grade_scales" as never).insert({organization_id:org,code:scaleForm.code.trim(),name:scaleForm.name.trim(),status:"active"} as never).select("*").single();if(error)throw error;const id=(data as unknown as Scale).id;const defaultRules=[{min_percentage:80,max_percentage:100,grade:4,label:"4",sequence_no:1},{min_percentage:75,max_percentage:79.99,grade:3.5,label:"3.5",sequence_no:2},{min_percentage:70,max_percentage:74.99,grade:3,label:"3",sequence_no:3},{min_percentage:65,max_percentage:69.99,grade:2.5,label:"2.5",sequence_no:4},{min_percentage:60,max_percentage:64.99,grade:2,label:"2",sequence_no:5},{min_percentage:55,max_percentage:59.99,grade:1.5,label:"1.5",sequence_no:6},{min_percentage:50,max_percentage:54.99,grade:1,label:"1",sequence_no:7},{min_percentage:0,max_percentage:49.99,grade:0,label:"0",sequence_no:8}];const{error:re}=await supabase.from("learning_grade_scale_rules" as never).insert(defaultRules.map(r=>({...r,grade_scale_id:id})) as never);if(re)throw re;return id},onSuccess:()=>{setScaleForm({code:"",name:""});void qc.invalidateQueries({queryKey:["learning","gradebook-settings-scales"]});}});
 const saveSubject=useMutation({mutationFn:async()=>{if(!selectedSubjectId)throw new Error("Select a subject.");const{error}=await supabase.from("learning_class_subjects" as never).update({grading_method:method,grade_scale_id:scaleId||null} as never).eq("id",selectedSubjectId);if(error)throw error},onSuccess:()=>void qc.invalidateQueries({queryKey:["learning","teacher-gradebook-class"]})});
 if(!user)return <div className="p-6">Sign in required.</div>;if(classQ.isPending)return <div className="h-64 animate-pulse rounded-2xl bg-slate-200"/>;
 return <div className="space-y-6"><div className="flex justify-between"><Link to={"/teacher/classes/"+classGroupId+"/gradebook"} className="inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={16}/>Back to Gradebook</Link></div>
 <section className="rounded-2xl bg-slate-900 p-6 text-white"><p className="text-sm text-slate-300">Gradebook settings</p><h1 className="mt-1 text-2xl font-bold">Academic grading configuration</h1><p className="mt-2 text-sm text-slate-300">Configure categories, grading method, and grade scale without changing the underlying academic model.</p></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><Settings size={18}/>Subject grading</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-sm font-medium">Subject<select value={selectedSubjectId} onChange={e=>setSubjectId(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2.5">{subjects.map(s=><option key={s.id} value={s.id}>{s.subject.name}</option>)}</select></label><label className="text-sm font-medium">Grading method<select value={method} onChange={e=>setMethod(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2.5"><option value="weighted_percentage">Weighted percentage</option><option value="points_total">Points total</option></select></label><label className="text-sm font-medium">Grade scale<select value={scaleId} onChange={e=>setScaleId(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2.5"><option value="">No scale</option>{(scales.data??[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><button type="button" onClick={()=>saveSubject.mutate()} className="mt-4 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white"><Save size={16} className="mr-2 inline"/>Save subject configuration</button></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Gradebook categories</h2><p className="mt-1 text-sm text-slate-500">Weights are configurable; do not hardcode curriculum-specific percentages.</p><div className="mt-4 grid gap-2 md:grid-cols-5"><input value={categoryForm.code} onChange={e=>setCategoryForm({...categoryForm,code:e.target.value})} placeholder="Code" className="rounded-xl border px-3 py-2.5 text-sm"/><input value={categoryForm.name} onChange={e=>setCategoryForm({...categoryForm,name:e.target.value})} placeholder="Category name" className="rounded-xl border px-3 py-2.5 text-sm"/><input value={categoryForm.weight} onChange={e=>setCategoryForm({...categoryForm,weight:e.target.value})} type="number" min="0" step="0.01" placeholder="Weight" className="rounded-xl border px-3 py-2.5 text-sm"/><input value={categoryForm.description} onChange={e=>setCategoryForm({...categoryForm,description:e.target.value})} placeholder="Description" className="rounded-xl border px-3 py-2.5 text-sm"/><button type="button" onClick={()=>updateCat.mutate()} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16} className="mr-2 inline"/>{categoryForm.id?"Update category":"Add category"}</button></div><div className="mt-5 divide-y border-t">{(cats.data??[]).map(c=><div key={c.id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><div><b>{c.name}</b><span className="ml-2 text-xs text-slate-500">{c.code} · weight {c.defaultWeight} · {c.status}</span></div><button type="button" onClick={()=>setCategoryForm({id:c.id,code:c.code,name:c.name,weight:String(c.defaultWeight),description:c.description??"",status:c.status})} className="rounded-lg border px-3 py-2 text-xs font-semibold">Edit</button></div>)}</div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Grade scales</h2><p className="mt-1 text-sm text-slate-500">New scales start with the standard 0–4 numeric rules and can be refined later.</p><div className="mt-4 flex flex-wrap gap-2"><input value={scaleForm.code} onChange={e=>setScaleForm({...scaleForm,code:e.target.value})} placeholder="Scale code" className="rounded-xl border px-3 py-2.5 text-sm"/><input value={scaleForm.name} onChange={e=>setScaleForm({...scaleForm,name:e.target.value})} placeholder="Scale name" className="rounded-xl border px-3 py-2.5 text-sm"/><button type="button" onClick={()=>createScale.mutate()} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Create scale</button></div><div className="mt-5 space-y-4">{(scales.data??[]).map(s=><div key={s.id} className="rounded-xl border p-4"><b>{s.name}</b><div className="mt-2 grid gap-2 text-xs text-slate-600 md:grid-cols-4">{(rules.data??[]).filter(r=>r.grade_scale_id===s.id).map(r=><span key={r.id}>{r.min_percentage}–{r.max_percentage}: Grade {r.label}</span>)}</div></div>)}</div></section>
 </div>
}