import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState, type ReactNode } from "react";
import { ArrowLeft, BookOpen, ClipboardCheck, FileQuestion, Plus, Send } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { useAuth } from "@/core/auth";
import { learningContentService } from "@/features/learning-content";
import { learningAssessmentService } from "@/features/learning-assessment";
import { learningAssignmentsService } from "@/features/learning-assignments";
import { learningTeacherService } from "../services/learning-teacher.service";

export default function TeacherAuthoringPage() {
  const { user } = useAuth();
  const qc = useQueryClient();
  const [classGroupId,setClassGroupId]=useState("");
  const [contentTitle,setContentTitle]=useState("");
  const [contentCode,setContentCode]=useState("");
  const [contentText,setContentText]=useState("");
  const [contentType,setContentType]=useState<"lesson"|"worksheet"|"reading">("lesson");
  const [questionCode,setQuestionCode]=useState("");
  const [questionPrompt,setQuestionPrompt]=useState("");
  const [questionType,setQuestionType]=useState<"single_choice"|"true_false"|"short_answer">("single_choice");
  const [questionConfig,setQuestionConfig]=useState("");
  const [objectiveId,setObjectiveId]=useState("");
  const [assessmentCode,setAssessmentCode]=useState("");
  const [assessmentTitle,setAssessmentTitle]=useState("");
  const [assessmentType,setAssessmentType]=useState<"quiz"|"test"|"practice">("quiz");
  const [selectedQuestionId,setSelectedQuestionId]=useState("");
  const [assignmentId,setAssignmentId]=useState("");
  const [selectedContentId,setSelectedContentId]=useState("");
  const [selectedAssessmentId,setSelectedAssessmentId]=useState("");
  const [searchParams]=useSearchParams();
  const [message,setMessage]=useState<string|null>(null);

  const classes=useQuery({queryKey:["learning","teacher-classes",user?.id],queryFn:()=>learningTeacherService.listTeacherClasses(user!.id),enabled:Boolean(user?.id)});
  const selected=classes.data?.find(x=>x.classGroup.id===classGroupId);
  const organizationId=selected?.membership.organizationId;
  const content=useQuery({queryKey:["learning","authoring","content",organizationId],queryFn:()=>learningContentService.listContent(organizationId),enabled:Boolean(organizationId)});
  const questions=useQuery({queryKey:["learning","authoring","questions",organizationId],queryFn:()=>learningAssessmentService.listQuestions(organizationId),enabled:Boolean(organizationId)});
  const assessments=useQuery({queryKey:["learning","authoring","assessments",organizationId],queryFn:()=>learningAssessmentService.listAssessments(organizationId),enabled:Boolean(organizationId)});
  const assignmentItems=useQuery({queryKey:["learning","authoring","assignment-items",assignmentId],queryFn:()=>learningAssignmentsService.listItems(assignmentId),enabled:Boolean(assignmentId)});
  const skills=useQuery({queryKey:["learning","authoring","skills"],queryFn:()=>learningContentService.listSkills(),enabled:Boolean(user)});
  const topics=useQuery({queryKey:["learning","authoring","topics"],queryFn:()=>learningContentService.listTopics(),enabled:Boolean(user)});
  const objectives=useQuery({queryKey:["learning","authoring","objectives"],queryFn:()=>learningContentService.listObjectives(),enabled:Boolean(user)});

  const createContent=useMutation({mutationFn:async()=>{if(!user||!organizationId)throw new Error("Select a teacher class first.");if(!contentTitle.trim()||!contentCode.trim()||!contentText.trim()||!objectiveId)throw new Error("Content title, code, body, and objective are required.");const item=await learningContentService.createContent({organizationId,code:contentCode.trim().toUpperCase(),title:contentTitle.trim(),contentType,languageCode:"en",createdBy:user.id});await learningContentService.createVersion({contentItemId:item.id,versionNo:1,body:{blocks:[{type:"text",text:contentText.trim()}]},changeSummary:"Initial authoring version",createdBy:user.id});await learningContentService.addObjective({contentItemId:item.id,objectiveId,sequenceNo:1});return item;},onSuccess:()=>{setMessage("Content saved as draft. Submit/review it before attaching it to a published assignment.");void qc.invalidateQueries({queryKey:["learning","authoring","content"]});setContentTitle("");setContentCode("");setContentText("");},onError:(e:Error)=>setMessage(e.message)});
  const publishContent=useMutation({mutationFn:(id:string)=>learningContentService.updateContentStatus(id,"published",user!.id),onSuccess:()=>{setMessage("Content published.");void qc.invalidateQueries({queryKey:["learning","authoring","content"]});},onError:(e:Error)=>setMessage(e.message)});
  const createQuestion=useMutation({mutationFn:async()=>{if(!user||!organizationId)throw new Error("Select a teacher class first.");if(!questionCode.trim()||!questionPrompt.trim()||!objectiveId)throw new Error("Question code, prompt, and objective are required.");let configuration:Record<string,unknown>={};if(questionConfig.trim())configuration=JSON.parse(questionConfig);const q=await learningAssessmentService.createQuestion({organizationId,code:questionCode.trim().toUpperCase(),questionType,createdBy:user.id});const v=await learningAssessmentService.createQuestionVersion({questionId:q.id,versionNo:1,prompt:{text:questionPrompt.trim()},configuration,createdBy:user.id});await learningAssessmentService.addQuestionObjective({questionVersionId:v.id,objectiveId,weight:1});return q;},onSuccess:()=>{setMessage("Question saved as draft.");void qc.invalidateQueries({queryKey:["learning","authoring","questions"]});setQuestionCode("");setQuestionPrompt("");setQuestionConfig("");},onError:(e:Error)=>setMessage(e.message)});
  const publishQuestion=useMutation({mutationFn:(id:string)=>learningAssessmentService.publishQuestion(id,user!.id),onSuccess:()=>{setMessage("Question published.");void qc.invalidateQueries({queryKey:["learning","authoring","questions"]});},onError:(e:Error)=>setMessage(e.message)});
  const createAssessment=useMutation({mutationFn:async()=>{if(!user||!organizationId)throw new Error("Select a teacher class first.");if(!assessmentCode.trim()||!assessmentTitle.trim()||!selectedQuestionId)throw new Error("Assessment code, title, and question are required.");const a=await learningAssessmentService.createAssessment({organizationId,code:assessmentCode.trim().toUpperCase(),title:assessmentTitle.trim(),assessmentType,languageCode:"en",createdBy:user.id});const versions=await learningAssessmentService.listQuestionVersions(selectedQuestionId);const version=versions[0];if(!version)throw new Error("Selected question has no version.");await learningAssessmentService.addAssessmentQuestion({assessmentId:a.id,questionVersionId:version.id,sequenceNo:1,points:1,required:true});return a;},onSuccess:()=>{setMessage("Assessment saved as draft.");void qc.invalidateQueries({queryKey:["learning","authoring","assessments"]});setAssessmentCode("");setAssessmentTitle("");},onError:(e:Error)=>setMessage(e.message)});
  const publishAssessment=useMutation({mutationFn:(id:string)=>learningAssessmentService.publishAssessment(id,user!.id),onSuccess:()=>{setMessage("Assessment published.");void qc.invalidateQueries({queryKey:["learning","authoring","assessments"]});},onError:(e:Error)=>setMessage(e.message)});
  const addAssignmentItem=useMutation({mutationFn:async(input:{itemType:"content"|"assessment";id:string})=>{if(!assignmentId||!organizationId)throw new Error("Create/select an assignment first.");return learningAssignmentsService.addItem({organizationId,assignmentId,itemType:input.itemType,contentItemId:input.itemType==="content"?input.id:null,assessmentId:input.itemType==="assessment"?input.id:null,sequenceNo:(assignmentItems.data?.length??0)+1,required:true});},onSuccess:()=>{setMessage("Learning item attached to assignment.");setSelectedContentId("");setSelectedAssessmentId("");void assignmentItems.refetch();},onError:(e:Error)=>setMessage(e.message)});
  const publishAssignment=useMutation({mutationFn:async()=>{if(!assignmentId)throw new Error("Enter an assignment ID.");return learningAssignmentsService.publishAssignment(assignmentId);},onSuccess:()=>setMessage("Assignment published after validating its learning items."),onError:(e:Error)=>setMessage(e.message)});

  if(!user)return <Panel title="Teacher authoring"><p>Sign in to continue.</p></Panel>;
  useEffect(()=>{const id=searchParams.get("assignmentId");if(id)setAssignmentId(id);},[searchParams]);
  if(classes.isPending)return <div className="h-64 animate-pulse rounded-2xl bg-slate-200"/>;
  if(classes.isError)return <Panel title="Teacher authoring"><p>Teacher classes could not be loaded.</p></Panel>;

  return <div className="mx-auto max-w-6xl space-y-6">
    <div><Link to="/teacher" className="inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={16}/>Back to teacher workspace</Link><h1 className="mt-3 text-2xl font-bold text-slate-900">Teacher authoring</h1><p className="mt-2 text-sm text-slate-500">Build reusable content, questions, assessments, and publish-ready assignment items.</p></div>
    <Panel title="Authoring context"><Field label="Teacher class"><select value={classGroupId} onChange={e=>setClassGroupId(e.target.value)} className="input"><option value="">Select a class</option>{classes.data?.map(x=><option key={x.classGroup.id} value={x.classGroup.id}>{x.classGroup.name}</option>)}</select></Field></Panel>
    {message&&<div className="rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-700">{message}</div>}
    <div className="grid gap-6 lg:grid-cols-2">
      <Panel title="Content library" icon={<BookOpen size={18}/>}>
        <div className="space-y-3"><Field label="Code"><input value={contentCode} onChange={e=>setContentCode(e.target.value)} className="input" placeholder="ENG-M1-LESSON-001"/></Field><Field label="Title"><input value={contentTitle} onChange={e=>setContentTitle(e.target.value)} className="input" placeholder="Present simple"/></Field><Field label="Type"><select value={contentType} onChange={e=>setContentType(e.target.value as typeof contentType)} className="input"><option value="lesson">Lesson</option><option value="worksheet">Worksheet</option><option value="reading">Reading</option></select></Field><Field label="Learning objective"><select value={objectiveId} onChange={e=>setObjectiveId(e.target.value)} className="input"><option value="">Select objective</option>{objectives.data?.map(o=><option key={o.id} value={o.id}>{o.code} — {o.name}</option>)}</select></Field><Field label="Body"><textarea value={contentText} onChange={e=>setContentText(e.target.value)} rows={5} className="input" placeholder="Write the learner-facing content..."/></Field><button disabled={!organizationId||createContent.isPending} onClick={()=>createContent.mutate()} className="btn"><Plus size={16}/>Create draft</button></div>
        <div className="mt-6 space-y-2">{content.data?.slice(0,8).map(c=><div key={c.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p className="font-medium">{c.title}</p><p className="text-xs text-slate-500">{c.code} · {c.status}</p></div>{c.status!=="published"&&<button onClick={()=>publishContent.mutate(c.id)} className="text-xs font-semibold text-slate-700">Publish</button>}</div>)}</div>
      </Panel>
      <Panel title="Question bank" icon={<FileQuestion size={18}/>}>
        <div className="space-y-3"><Field label="Code"><input value={questionCode} onChange={e=>setQuestionCode(e.target.value)} className="input" placeholder="ENG-M1-Q001"/></Field><Field label="Type"><select value={questionType} onChange={e=>setQuestionType(e.target.value as typeof questionType)} className="input"><option value="single_choice">Single choice</option><option value="true_false">True / False</option><option value="short_answer">Short answer</option></select></Field><Field label="Prompt"><textarea value={questionPrompt} onChange={e=>setQuestionPrompt(e.target.value)} rows={4} className="input" placeholder="Choose the correct answer..."/></Field><Field label="Configuration JSON"><textarea value={questionConfig} onChange={e=>setQuestionConfig(e.target.value)} rows={3} className="input" placeholder='{"options":["A","B","C"],"correctAnswer":"A"}'/></Field><Field label="Learning objective"><select value={objectiveId} onChange={e=>setObjectiveId(e.target.value)} className="input"><option value="">Select objective</option>{objectives.data?.map(o=><option key={o.id} value={o.id}>{o.code} — {o.name}</option>)}</select></Field><button disabled={!organizationId||createQuestion.isPending} onClick={()=>createQuestion.mutate()} className="btn"><Plus size={16}/>Create question</button></div>
        <div className="mt-6 space-y-2">{questions.data?.slice(0,8).map(q=><div key={q.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p className="font-medium">{q.code}</p><p className="text-xs text-slate-500">{q.questionType} · {q.status}</p></div>{q.status!=="published"&&<button onClick={()=>publishQuestion.mutate(q.id)} className="text-xs font-semibold text-slate-700">Publish</button>}</div>)}</div>
      </Panel>
      <Panel title="Assessment builder" icon={<ClipboardCheck size={18}/>}>
        <div className="space-y-3"><Field label="Code"><input value={assessmentCode} onChange={e=>setAssessmentCode(e.target.value)} className="input" placeholder="ENG-M1-QZ-001"/></Field><Field label="Title"><input value={assessmentTitle} onChange={e=>setAssessmentTitle(e.target.value)} className="input" placeholder="Present simple quiz"/></Field><Field label="Type"><select value={assessmentType} onChange={e=>setAssessmentType(e.target.value as typeof assessmentType)} className="input"><option value="practice">Practice</option><option value="quiz">Quiz</option><option value="test">Test</option></select></Field><Field label="Question"><select value={selectedQuestionId} onChange={e=>setSelectedQuestionId(e.target.value)} className="input"><option value="">Select question</option>{questions.data?.map(q=><option key={q.id} value={q.id}>{q.code} — {q.status}</option>)}</select></Field><button disabled={!organizationId||createAssessment.isPending} onClick={()=>createAssessment.mutate()} className="btn"><Plus size={16}/>Create draft assessment</button></div>
        <div className="mt-6 space-y-2">{assessments.data?.slice(0,8).map(a=><div key={a.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p className="font-medium">{a.title}</p><p className="text-xs text-slate-500">{a.code} · {a.status}</p></div>{a.status!=="published"&&<button onClick={()=>publishAssessment.mutate(a.id)} className="text-xs font-semibold text-slate-700">Publish</button>}</div>)}</div>
      </Panel>
      <Panel title="Assignment builder" icon={<Send size={18}/>}>
        <p className="text-sm text-slate-600">Attach published content or assessments to the draft assignment. Publishing is blocked until at least one valid item is attached.</p><Field label="Assignment ID"><input value={assignmentId} onChange={e=>setAssignmentId(e.target.value)} className="input" placeholder="Assignment UUID"/></Field>
        <div className="grid gap-3 sm:grid-cols-2"><Field label="Content"><select value={selectedContentId} onChange={e=>setSelectedContentId(e.target.value)} className="input"><option value="">Select content</option>{content.data?.filter(x=>x.status==="published").map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></Field><button disabled={!selectedContentId||addAssignmentItem.isPending} onClick={()=>addAssignmentItem.mutate({itemType:"content",id:selectedContentId})} className="btn self-end"><Plus size={16}/>Attach content</button><Field label="Assessment"><select value={selectedAssessmentId} onChange={e=>setSelectedAssessmentId(e.target.value)} className="input"><option value="">Select assessment</option>{assessments.data?.filter(x=>x.status==="published").map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></Field><button disabled={!selectedAssessmentId||addAssignmentItem.isPending} onClick={()=>addAssignmentItem.mutate({itemType:"assessment",id:selectedAssessmentId})} className="btn self-end"><Plus size={16}/>Attach assessment</button></div>
        <div className="mt-4 space-y-2">{assignmentItems.data?.map(i=><div key={i.id} className="rounded-xl bg-slate-50 p-3 text-sm">{i.itemType} · sequence {i.sequenceNo}</div>)}</div>
        <button disabled={!assignmentId||publishAssignment.isPending} onClick={()=>publishAssignment.mutate()} className="btn mt-4"><Send size={16}/>Validate & publish assignment</button>
      </Panel>
    </div>
    <p className="text-xs text-slate-400">The academic catalog currently contains {skills.data?.length??0} skills, {topics.data?.length??0} topics, and {objectives.data?.length??0} learning objectives.</p>
  </div>;
}
function Panel({title,icon,children}:{title:string;icon?:ReactNode;children:ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-semibold text-slate-900">{icon}{title}</h2><div className="mt-4">{children}</div></section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block space-y-2"><span className="text-sm font-medium text-slate-700">{label}</span>{children}</label>}
