import type { Database, Json } from "@/core/database/database.types";
import { supabase } from "@/core/infrastructure/supabase/client";
import type { LearningAssignment,LearningAssignmentInput,LearningAssignmentItem,LearningAssignmentItemInput,LearningAssignmentProgress,LearningAssignmentProgressInput,LearningAssignmentTarget,LearningAssignmentTargetInput,LearningAssignmentLifecycleEvent } from "../types/learning-assignments.types";
type AssignmentRow=Database["public"]["Tables"]["learning_assignments"]["Row"];type ItemRow=Database["public"]["Tables"]["learning_assignment_items"]["Row"];type TargetRow=Database["public"]["Tables"]["learning_assignment_targets"]["Row"];type ProgressRow=Database["public"]["Tables"]["learning_assignment_progress"]["Row"];
const rec=(v:Json):Record<string,unknown>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};
const mapA=(r:AssignmentRow & {parent_assignment_id?:string|null;lifecycle_type?:string}):LearningAssignment=>({id:r.id,tenantId:r.tenant_id,organizationId:r.organization_id,classSubjectId:r.class_subject_id,code:r.code,title:r.title,description:r.description,status:r.status as LearningAssignment["status"],availableFrom:r.available_from,dueAt:r.due_at,maxAttempts:r.max_attempts,instructions:rec(r.instructions),createdBy:r.created_by,updatedBy:r.updated_by,createdAt:r.created_at,updatedAt:r.updated_at,parentAssignmentId:r.parent_assignment_id??null,lifecycleType:(r.lifecycle_type??"original") as LearningAssignment["lifecycleType"]});
const mapI=(r:ItemRow):LearningAssignmentItem=>({id:r.id,organizationId:r.organization_id,assignmentId:r.assignment_id,itemType:r.item_type as LearningAssignmentItem["itemType"],contentItemId:r.content_item_id,assessmentId:r.assessment_id,sequenceNo:r.sequence_no,required:r.required,createdAt:r.created_at});
const mapT=(r:TargetRow):LearningAssignmentTarget=>({id:r.id,tenantId:r.tenant_id,organizationId:r.organization_id,assignmentId:r.assignment_id,targetType:r.target_type as LearningAssignmentTarget["targetType"],studentUserId:r.student_user_id,classGroupId:r.class_group_id,dueAt:r.due_at,status:r.status as LearningAssignmentTarget["status"],createdAt:r.created_at,updatedAt:r.updated_at});
const mapP=(r:ProgressRow):LearningAssignmentProgress=>({id:r.id,organizationId:r.organization_id,assignmentId:r.assignment_id,assignmentTargetId:r.assignment_target_id,studentUserId:r.student_user_id,status:r.status as LearningAssignmentProgress["status"],startedAt:r.started_at,completedAt:r.completed_at,lastActivityAt:r.last_activity_at,createdAt:r.created_at,updatedAt:r.updated_at});
async function listAccessibleTargets(studentUserId:string){
  const [{data:directTargets,error:directError},{data:memberships,error:membershipError}]=await Promise.all([
    supabase.from("learning_assignment_targets").select("*").eq("student_user_id",studentUserId).eq("status","active"),
    supabase.from("learning_class_memberships").select("class_group_id").eq("user_id",studentUserId).eq("membership_type","student").eq("status","active"),
  ]);
  if(directError)throw directError;if(membershipError)throw membershipError;
  const classGroupIds=[...new Set((memberships??[]).map(row=>row.class_group_id))].filter((v):v is string=>Boolean(v));
  let classTargets:TargetRow[]=[];
  if(classGroupIds.length){const{data,error}=await supabase.from("learning_assignment_targets").select("*").in("class_group_id",classGroupIds).eq("status","active");if(error)throw error;classTargets=data??[];}
  return [...(directTargets??[]),...classTargets].map(mapT);
}
export const learningAssignmentsRepository={
 async listStudentAssignments(studentUserId:string){const targets=await listAccessibleTargets(studentUserId);const ids=[...new Set(targets.map(target=>target.assignmentId))];if(!ids.length)return[];const{data,error}=await supabase.from("learning_assignments").select("*").eq("status","published").in("id",ids).order("due_at",{ascending:true,nullsFirst:false});if(error)throw error;return(data??[]).map(mapA);},
 async getStudentAssignment(assignmentId:string,studentUserId:string){const[assignments,items,progress]=await Promise.all([learningAssignmentsRepository.listStudentAssignments(studentUserId),learningAssignmentsRepository.listItems(assignmentId),learningAssignmentsRepository.listProgress(studentUserId)]);const assignment=assignments.find(x=>x.id===assignmentId);if(!assignment)throw new Error("Assignment is not available to this student.");return{assignment,items,progress:progress.find(x=>x.assignmentId===assignmentId)??null};},
 async startForStudent(assignmentId:string,studentUserId:string){const targets=await listAccessibleTargets(studentUserId);const target=targets.find(x=>x.assignmentId===assignmentId);if(!target)throw new Error("No active assignment target was found for this student.");return learningAssignmentsRepository.ensureProgress({organizationId:target.organizationId,assignmentId,assignmentTargetId:target.id,studentUserId}).then(p=>p.status==="not_started"?learningAssignmentsRepository.updateProgress(p.id,"in_progress"):p);},
 async listAssignmentHistoryForClass(classGroupId:string){
  const[{data:targets,error:targetError},{data:classSubjects,error:classSubjectError}]=await Promise.all([
    supabase.from("learning_assignment_targets").select("assignment_id").eq("class_group_id",classGroupId),
    supabase.from("learning_class_subjects").select("id").eq("class_group_id",classGroupId),
  ]);
  if(targetError)throw targetError;if(classSubjectError)throw classSubjectError;
  const classSubjectIds=(classSubjects??[]).map(x=>x.id);
  const ids=new Set((targets??[]).map(x=>x.assignment_id));
  if(classSubjectIds.length){
    const{data:subjectAssignments,error}=await supabase.from("learning_assignments").select("id").in("class_subject_id",classSubjectIds);
    if(error)throw error;(subjectAssignments??[]).forEach(x=>ids.add(x.id));
  }
  const assignmentIds=[...ids];if(!assignmentIds.length)return[];
  const{data,error:assignmentError}=await supabase.from("learning_assignments").select("*").in("id",assignmentIds).order("updated_at",{ascending:false});
  if(assignmentError)throw assignmentError;
  return(data??[]).map(row=>mapA(row as AssignmentRow & {parent_assignment_id?:string|null;lifecycle_type?:string}));
},
async reopenAssignment(id:string){const{data,error}=await supabase.rpc("reopen_learning_assignment",{p_assignment_id:id});if(error)throw error;const{data:assignment,error:assignmentError}=await supabase.from("learning_assignments").select("*").eq("id",data).single();if(assignmentError)throw assignmentError;return mapA(assignment as AssignmentRow & {parent_assignment_id?:string|null;lifecycle_type?:string});},
async closeAssignment(id:string){const{data,error}=await supabase.rpc("close_learning_assignment",{p_assignment_id:id});if(error)throw error;const{data:assignment,error:assignmentError}=await supabase.from("learning_assignments").select("*").eq("id",data).single();if(assignmentError)throw assignmentError;return mapA(assignment as AssignmentRow & {parent_assignment_id?:string|null;lifecycle_type?:string});},
async reassignToStudent(id:string,studentUserId:string,dueAt:string|null){const{data,error}=await supabase.rpc("reassign_learning_assignment",{p_assignment_id:id,p_student_user_id:studentUserId,p_due_at:dueAt ?? undefined});if(error)throw error;const{data:assignment,error:assignmentError}=await supabase.from("learning_assignments").select("*").eq("id",data).single();if(assignmentError)throw assignmentError;const items=await learningAssignmentsRepository.listItems(data);return{assignment:mapA(assignment as AssignmentRow & {parent_assignment_id?:string|null;lifecycle_type?:string}),items};},
async listLifecycleEventsForAssignments(assignmentIds:string[]):Promise<LearningAssignmentLifecycleEvent[]>{
  if(!assignmentIds.length)return[];
  const{data,error}=await supabase.from("learning_assignment_lifecycle_events" as never).select("*").in("assignment_id",assignmentIds).order("created_at",{ascending:false});
  if(error)throw error;
  return(data??[]).map((r:any)=>({id:r.id,assignmentId:r.assignment_id,parentAssignmentId:r.parent_assignment_id??null,action:r.action,targetStudentUserId:r.target_student_user_id??null,actorUserId:r.actor_user_id,metadata:r.metadata&&typeof r.metadata==="object"?r.metadata:{},createdAt:r.created_at}));
},
async listAssignmentsForClass(classGroupId:string){const{data:targets,error}=await supabase.from("learning_assignment_targets").select("assignment_id").eq("class_group_id",classGroupId).eq("status","active");if(error)throw error;const ids=[...new Set((targets??[]).map(x=>x.assignment_id))];if(!ids.length)return[];const{data,error:assignmentError}=await supabase.from("learning_assignments").select("*").in("id",ids).order("updated_at",{ascending:false});if(assignmentError)throw assignmentError;return(data??[]).map(mapA);},
 async listItems(id:string){const{data,error}=await supabase.from("learning_assignment_items").select("*").eq("assignment_id",id).order("sequence_no");if(error)throw error;return(data??[]).map(mapI);},
 async findStudentAssignmentForAssessment(assessmentId:string,studentUserId:string){
  const assignments=await learningAssignmentsRepository.listStudentAssignments(studentUserId);
  const{data:attempts,error}=await supabase.from("learning_attempts").select("assessment_id").eq("student_user_id",studentUserId).eq("assessment_id",assessmentId);
  if(error)throw error;
  const attemptCount=(attempts??[]).length;
  for(const assignment of assignments){const items=await learningAssignmentsRepository.listItems(assignment.id);if(!items.some(item=>item.assessmentId===assessmentId))continue;const maxAttempts=assignment.maxAttempts;if(maxAttempts===null||attemptCount<maxAttempts)return assignment;}
  return null;
},
async completeIfReady(assignmentId:string,studentUserId:string){
  const{items,progress}=await learningAssignmentsRepository.getStudentAssignment(assignmentId,studentUserId);
  if(!progress||progress.status==="completed")return progress;
  const requiredAssessmentIds=items.filter(item=>item.required&&item.itemType==="assessment").map(item=>item.assessmentId).filter((v):v is string=>Boolean(v));
  if(!requiredAssessmentIds.length)return progress;
  const{data:attempts,error}=await supabase.from("learning_attempts").select("assessment_id,status").eq("student_user_id",studentUserId).in("assessment_id",requiredAssessmentIds);
  if(error)throw error;
  const evaluated=new Set((attempts??[]).filter(attempt=>attempt.status==="evaluated").map(attempt=>attempt.assessment_id));
  if(!requiredAssessmentIds.every(id=>evaluated.has(id)))return progress;
  return learningAssignmentsRepository.updateProgress(progress.id,"completed");
},
 async listTargets(id:string){const{data,error}=await supabase.from("learning_assignment_targets").select("*").eq("assignment_id",id).eq("status","active");if(error)throw error;return(data??[]).map(mapT);},
 async listProgress(studentUserId:string){const{data,error}=await supabase.from("learning_assignment_progress").select("*").eq("student_user_id",studentUserId).order("last_activity_at",{ascending:false,nullsFirst:false});if(error)throw error;return(data??[]).map(mapP);},
 async listProgressForAssignment(id:string){const{data,error}=await supabase.from("learning_assignment_progress").select("*").eq("assignment_id",id).order("last_activity_at",{ascending:false,nullsFirst:false});if(error)throw error;return(data??[]).map(mapP);},
 async createAssignment(input:LearningAssignmentInput){const{data,error}=await supabase.from("learning_assignments").insert({tenant_id:input.tenantId,organization_id:input.organizationId,class_subject_id:input.classSubjectId??null,code:input.code,title:input.title,description:input.description??null,status:input.status??"draft",available_from:input.availableFrom??null,due_at:input.dueAt??null,max_attempts:input.maxAttempts??null,instructions:(input.instructions??{}) as Json,created_by:input.createdBy}).select("*").single();if(error)throw error;return mapA(data);},
 async addItem(input:LearningAssignmentItemInput){const{data,error}=await supabase.from("learning_assignment_items").insert({organization_id:input.organizationId,assignment_id:input.assignmentId,item_type:input.itemType,content_item_id:input.contentItemId??null,assessment_id:input.assessmentId??null,sequence_no:input.sequenceNo,required:input.required??true}).select("*").single();if(error)throw error;return mapI(data);},
 async addTarget(input:LearningAssignmentTargetInput){const{data,error}=await supabase.from("learning_assignment_targets").insert({tenant_id:input.tenantId,organization_id:input.organizationId,assignment_id:input.assignmentId,target_type:input.targetType,student_user_id:input.studentUserId??null,class_group_id:input.classGroupId??null,due_at:input.dueAt??null}).select("*").single();if(error)throw error;return mapT(data);},
 async ensureProgress(input:LearningAssignmentProgressInput){const{data,error}=await supabase.from("learning_assignment_progress").upsert({organization_id:input.organizationId,assignment_id:input.assignmentId,assignment_target_id:input.assignmentTargetId,student_user_id:input.studentUserId},{onConflict:"assignment_target_id,student_user_id"}).select("*").single();if(error)throw error;return mapP(data);},
 async updateAssignmentStatus(id:string,status:LearningAssignment["status"]){const{data,error}=await supabase.from("learning_assignments").update({status}).eq("id",id).select("*").single();if(error)throw error;return mapA(data);},
 async publishAssignment(id:string){const{data:items,error:itemsError}=await supabase.from("learning_assignment_items").select("item_type,content_item_id,assessment_id").eq("assignment_id",id);if(itemsError)throw itemsError;if(!(items??[]).length)throw new Error("An assignment needs at least one learning item before publishing.");const contentIds=(items??[]).filter(i=>i.item_type==="content"&&i.content_item_id).map(i=>i.content_item_id as string);const assessmentIds=(items??[]).filter(i=>i.item_type==="assessment"&&i.assessment_id).map(i=>i.assessment_id as string);if(contentIds.length){const{data:content,error}=await supabase.from("learning_content_items").select("id,status").in("id",contentIds);if(error)throw error;if((content??[]).length!==contentIds.length||content.some(x=>x.status!=="published"))throw new Error("Every content item must be published before the assignment can be published.");}if(assessmentIds.length){const{data:assessments,error}=await supabase.from("learning_assessments").select("id,status").in("id",assessmentIds);if(error)throw error;if((assessments??[]).length!==assessmentIds.length||assessments.some(x=>x.status!=="published"))throw new Error("Every assessment must be published before the assignment can be published.");const{data:existingItems,error:existingItemsError}=await supabase.from("learning_assignment_items").select("assignment_id,assessment_id").in("assessment_id",assessmentIds).neq("assignment_id",id);if(existingItemsError)throw existingItemsError;const existingIds=[...new Set((existingItems??[]).map(item=>item.assignment_id))];if(existingIds.length){const{data:existingAssignments,error:existingAssignmentsError}=await supabase.from("learning_assignments").select("id,status").in("id",existingIds).eq("status","published");if(existingAssignmentsError)throw existingAssignmentsError;if((existingAssignments??[]).length)throw new Error("This assessment is already attached to a published assignment. Create or select a different assessment before publishing this assignment.");}}return learningAssignmentsRepository.updateAssignmentStatus(id,"published");},
 async updateProgress(id:string,status:LearningAssignmentProgress["status"]){const now=new Date().toISOString();const patch:Database["public"]["Tables"]["learning_assignment_progress"]["Update"]={status,last_activity_at:now};if(status==="in_progress")patch.started_at=now;if(status==="completed")patch.completed_at=now;const{data,error}=await supabase.from("learning_assignment_progress").update(patch).eq("id",id).select("*").single();if(error)throw error;return mapP(data);},
 async refreshProgressForStudent(assignmentId:string,studentUserId:string){const result=await learningAssignmentsRepository.getStudentAssignment(assignmentId,studentUserId);const progress=await learningAssignmentsRepository.startForStudent(assignmentId,studentUserId);const requiredItems=result.items.filter(x=>x.required);if(!requiredItems.length){if(progress.status==="completed")return progress;return learningAssignmentsRepository.updateProgress(progress.id,"completed");}const requiredContentIds=requiredItems.filter(x=>x.itemType==="content"&&x.contentItemId).map(x=>x.contentItemId as string);const requiredAssessmentIds=requiredItems.filter(x=>x.itemType==="assessment"&&x.assessmentId).map(x=>x.assessmentId as string);const completedContentIds=new Set<string>();if(requiredContentIds.length){const{data,error}=await supabase.from("learning_activity_events").select("content_item_id,metadata").eq("assignment_id",assignmentId).eq("student_user_id",studentUserId).eq("activity_type","content_viewed").in("content_item_id",requiredContentIds);if(error)throw error;for(const event of data??[]){const metadata=event.metadata as Record<string,unknown>;if(event.content_item_id&&metadata?.completion==="completed")completedContentIds.add(event.content_item_id);}}const evaluatedAssessmentIds=new Set<string>();if(requiredAssessmentIds.length){const{data:attempts,error:attemptError}=await supabase.from("learning_attempts").select("id,assessment_id").eq("student_user_id",studentUserId).in("assessment_id",requiredAssessmentIds);if(attemptError)throw attemptError;const attemptIds=(attempts??[]).map(attempt=>attempt.id);if(attemptIds.length){const{data:results,error:resultError}=await supabase.from("learning_assessment_results").select("attempt_id").in("attempt_id",attemptIds);if(resultError)throw resultError;const assessmentByAttempt=new Map((attempts??[]).map(attempt=>[attempt.id,attempt.assessment_id]));for(const resultRow of results??[]){const assessmentId=assessmentByAttempt.get(resultRow.attempt_id);if(assessmentId)evaluatedAssessmentIds.add(assessmentId);}}}const allRequiredCompleted=requiredItems.every(item=>item.itemType==="content"?Boolean(item.contentItemId&&completedContentIds.has(item.contentItemId)):Boolean(item.assessmentId&&evaluatedAssessmentIds.has(item.assessmentId)));if(allRequiredCompleted){if(progress.status==="completed")return progress;return learningAssignmentsRepository.updateProgress(progress.id,"completed");}if(progress.status==="completed")return learningAssignmentsRepository.updateProgress(progress.id,"in_progress");return progress;},
 async completeContentForStudent(assignmentId:string,contentItemId:string,studentUserId:string){const result=await learningAssignmentsRepository.getStudentAssignment(assignmentId,studentUserId);const item=result.items.find(x=>x.itemType==="content"&&x.contentItemId===contentItemId);if(!item)throw new Error("This learning content is not part of the assignment.");if(!item.required)throw new Error("Optional learning content does not complete the assignment by itself.");const{error}=await supabase.from("learning_activity_events").insert({tenant_id:result.assignment.tenantId,organization_id:result.assignment.organizationId,student_user_id:studentUserId,activity_type:"content_viewed",content_item_id:contentItemId,assignment_id:assignmentId,metadata:{completion:"completed"}});if(error)throw error;return learningAssignmentsRepository.refreshProgressForStudent(assignmentId,studentUserId);},

};