import type { Database, Json } from "@/core/database/database.types";
import { supabase } from "@/core/infrastructure/supabase/client";
import type { LearningAssessment,LearningAssessmentQuestion,LearningAssessmentResult,LearningAttempt,LearningAttemptAnswer,LearningAttemptAnswerInput,LearningAssessmentInsert,LearningQuestion,LearningQuestionInsert,LearningQuestionObjective,LearningQuestionVersion,LearningQuestionType } from "../types/learning-assessment.types";
type QuestionRow=Database["public"]["Tables"]["learning_questions"]["Row"];type QuestionVersionRow=Database["public"]["Tables"]["learning_question_versions"]["Row"];type QuestionObjectiveRow=Database["public"]["Tables"]["learning_question_objectives"]["Row"];type AssessmentRow=Database["public"]["Tables"]["learning_assessments"]["Row"];type AssessmentQuestionRow=Database["public"]["Tables"]["learning_assessment_questions"]["Row"];type AttemptRow=Database["public"]["Tables"]["learning_attempts"]["Row"];type AnswerRow=Database["public"]["Tables"]["learning_attempt_answers"]["Row"];type ResultRow=Database["public"]["Tables"]["learning_assessment_results"]["Row"];
export interface LearningAssessmentRepository{listQuestions(organizationId?:string):Promise<LearningQuestion[]>;listQuestionVersions(questionId:string):Promise<LearningQuestionVersion[]>;listQuestionObjectives(questionVersionId:string):Promise<LearningQuestionObjective[]>;listAssessments(organizationId?:string):Promise<LearningAssessment[]>;listAssessmentQuestions(assessmentId:string):Promise<LearningAssessmentQuestion[]>;listAttempts(studentUserId:string):Promise<LearningAttempt[]>;listAttemptAnswers(attemptId:string):Promise<LearningAttemptAnswer[]>;listResults(studentUserId:string):Promise<LearningAssessmentResult[]>;createQuestion(input:LearningQuestionInsert&{createdBy:string}):Promise<LearningQuestion>;createQuestionVersion(input:{questionId:string;versionNo:number;prompt:Record<string,unknown>;configuration:Record<string,unknown>;explanation?:Record<string,unknown>|null;createdBy:string}):Promise<LearningQuestionVersion>;addQuestionObjective(input:{questionVersionId:string;objectiveId:string;weight?:number}):Promise<LearningQuestionObjective>;createAssessment(input:LearningAssessmentInsert&{createdBy:string}):Promise<LearningAssessment>;addAssessmentQuestion(input:{assessmentId:string;questionVersionId:string;sequenceNo:number;points:number;required:boolean}):Promise<LearningAssessmentQuestion>;updateQuestionStatus(id:string,status:LearningQuestion["status"],reviewerId?:string):Promise<LearningQuestion>;updateAssessmentStatus(id:string,status:LearningAssessment["status"],reviewerId?:string):Promise<LearningAssessment>;createAttempt(input:{tenantId:string;organizationId:string|null;assessmentId:string;studentUserId:string;attemptNumber:number;previousAttemptId?:string|null}):Promise<LearningAttempt>;saveAnswer(input:LearningAttemptAnswerInput):Promise<LearningAttemptAnswer>;submitAttempt(attemptId:string):Promise<LearningAttempt>}
const obj=(v:Json|null):Record<string,unknown>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};
const mq=(r:QuestionRow):LearningQuestion=>({id:r.id,organizationId:r.organization_id,code:r.code,questionType:r.question_type as LearningQuestion["questionType"],languageCode:r.language_code,status:r.status as LearningQuestion["status"],createdBy:r.created_by,updatedBy:r.updated_by,reviewedBy:r.reviewed_by,reviewedAt:r.reviewed_at,createdAt:r.created_at,updatedAt:r.updated_at});
const mqv=(r:QuestionVersionRow):LearningQuestionVersion=>({id:r.id,questionId:r.question_id,versionNo:r.version_no,prompt:obj(r.prompt),configuration:obj(r.configuration),explanation:r.explanation?obj(r.explanation):null,createdBy:r.created_by,reviewedBy:r.reviewed_by,reviewedAt:r.reviewed_at,publishedAt:r.published_at,createdAt:r.created_at,updatedAt:r.updated_at});
const mqo=(r:QuestionObjectiveRow):LearningQuestionObjective=>({questionVersionId:r.question_version_id,objectiveId:r.objective_id,weight:r.weight,createdAt:r.created_at});
const ma=(r:AssessmentRow):LearningAssessment=>({id:r.id,organizationId:r.organization_id,code:r.code,title:r.title,description:r.description,assessmentType:r.assessment_type as LearningAssessment["assessmentType"],languageCode:r.language_code,curriculumId:r.curriculum_id,gradeLevelId:r.grade_level_id,status:r.status as LearningAssessment["status"],createdBy:r.created_by,updatedBy:r.updated_by,reviewedBy:r.reviewed_by,reviewedAt:r.reviewed_at,publishedAt:r.published_at,createdAt:r.created_at,updatedAt:r.updated_at});
const maq=(r:AssessmentQuestionRow):LearningAssessmentQuestion=>({id:r.id,assessmentId:r.assessment_id,questionVersionId:r.question_version_id,sequenceNo:r.sequence_no,points:r.points,required:r.required,createdAt:r.created_at});
const mat=(r:AttemptRow):LearningAttempt=>({id:r.id,tenantId:r.tenant_id,organizationId:r.organization_id,assessmentId:r.assessment_id,studentUserId:r.student_user_id,attemptNumber:r.attempt_number,previousAttemptId:r.previous_attempt_id,status:r.status as LearningAttempt["status"],startedAt:r.started_at,submittedAt:r.submitted_at,score:r.score,maxScore:r.max_score,percentage:r.percentage,createdAt:r.created_at,updatedAt:r.updated_at});
const maa=(r:AnswerRow):LearningAttemptAnswer=>({id:r.id,attemptId:r.attempt_id,assessmentQuestionId:r.assessment_question_id,answer:obj(r.answer),evaluationStatus:r.evaluation_status as LearningAttemptAnswer["evaluationStatus"],isCorrect:r.is_correct,awardedPoints:r.awarded_points,feedback:r.feedback?obj(r.feedback):null,evaluatedAt:r.evaluated_at,createdAt:r.created_at,updatedAt:r.updated_at});
const mr=(r:ResultRow):LearningAssessmentResult=>({id:r.id,attemptId:r.attempt_id,studentUserId:r.student_user_id,organizationId:r.organization_id,score:r.score,maxScore:r.max_score,percentage:r.percentage,passed:r.passed,evaluatedAt:r.evaluated_at,summary:obj(r.summary),createdAt:r.created_at,updatedAt:r.updated_at});
export const learningAssessmentRepository:LearningAssessmentRepository={
 async listQuestions(org){let q=supabase.from("learning_questions").select("*").order("updated_at",{ascending:false});if(org)q=q.eq("organization_id",org);const{data,error}=await q;if(error)throw error;return(data??[]).map(mq);},
 async listQuestionVersions(id){const{data,error}=await supabase.from("learning_question_versions").select("*").eq("question_id",id).order("version_no",{ascending:false});if(error)throw error;return(data??[]).map(mqv);},
 async listQuestionObjectives(id){const{data,error}=await supabase.from("learning_question_objectives").select("*").eq("question_version_id",id);if(error)throw error;return(data??[]).map(mqo);},
 async listAssessments(org){let q=supabase.from("learning_assessments").select("*").order("updated_at",{ascending:false});if(org)q=q.eq("organization_id",org);const{data,error}=await q;if(error)throw error;return(data??[]).map(ma);},
 async listAssessmentQuestions(id){const{data,error}=await supabase.from("learning_assessment_questions").select("*").eq("assessment_id",id).order("sequence_no");if(error)throw error;return(data??[]).map(maq);},
 async listAttempts(id){const{data,error}=await supabase.from("learning_attempts").select("*").eq("student_user_id",id).order("created_at",{ascending:false});if(error)throw error;return(data??[]).map(mat);},
 async listAttemptAnswers(id){const{data,error}=await supabase.from("learning_attempt_answers").select("*").eq("attempt_id",id);if(error)throw error;return(data??[]).map(maa);},
 async listResults(id){const{data,error}=await supabase.from("learning_assessment_results").select("*").eq("student_user_id",id).order("evaluated_at",{ascending:false});if(error)throw error;return(data??[]).map(mr);},
 async createQuestion(input){const{data,error}=await supabase.from("learning_questions").insert({organization_id:input.organizationId,code:input.code,question_type:input.questionType,language_code:input.languageCode??"en",created_by:input.createdBy}).select("*").single();if(error)throw error;return mq(data);},
 async createQuestionVersion(input){const{data,error}=await supabase.from("learning_question_versions").insert({question_id:input.questionId,version_no:input.versionNo,prompt:input.prompt as Json,configuration:input.configuration as Json,explanation:(input.explanation??null) as Json,created_by:input.createdBy}).select("*").single();if(error)throw error;return mqv(data);},
 async addQuestionObjective(input){const{data,error}=await supabase.from("learning_question_objectives").insert({question_version_id:input.questionVersionId,objective_id:input.objectiveId,weight:input.weight??1}).select("*").single();if(error)throw error;return mqo(data);},
 async createAssessment(input){const{data,error}=await supabase.from("learning_assessments").insert({organization_id:input.organizationId,code:input.code,title:input.title,description:input.description??null,assessment_type:input.assessmentType,language_code:input.languageCode??"en",curriculum_id:input.curriculumId??null,grade_level_id:input.gradeLevelId??null,created_by:input.createdBy}).select("*").single();if(error)throw error;return ma(data);},
 async addAssessmentQuestion(input){const{data,error}=await supabase.from("learning_assessment_questions").insert({assessment_id:input.assessmentId,question_version_id:input.questionVersionId,sequence_no:input.sequenceNo,points:input.points,required:input.required}).select("*").single();if(error)throw error;return maq(data);},
 async updateQuestionStatus(id,status,reviewerId){const patch:Database["public"]["Tables"]["learning_questions"]["Update"]={status};if(reviewerId){patch.reviewed_by=reviewerId;patch.reviewed_at=new Date().toISOString();}const{data,error}=await supabase.from("learning_questions").update(patch).eq("id",id).select("*").single();if(error)throw error;return mq(data);},
 async updateAssessmentStatus(id,status,reviewerId){const patch:Database["public"]["Tables"]["learning_assessments"]["Update"]={status};if(reviewerId){patch.reviewed_by=reviewerId;patch.reviewed_at=new Date().toISOString();}if(status==="published")patch.published_at=new Date().toISOString();const{data,error}=await supabase.from("learning_assessments").update(patch).eq("id",id).select("*").single();if(error)throw error;return ma(data);},
 async createAttempt(input){const{data,error}=await supabase.from("learning_attempts").insert({tenant_id:input.tenantId,organization_id:input.organizationId,assessment_id:input.assessmentId,student_user_id:input.studentUserId,attempt_number:input.attemptNumber,previous_attempt_id:input.previousAttemptId??null}).select("*").single();if(error)throw error;return mat(data);},
 async saveAnswer(input){const{data,error}=await supabase.from("learning_attempt_answers").upsert({attempt_id:input.attemptId,assessment_question_id:input.assessmentQuestionId,answer:input.answer as Json},{onConflict:"attempt_id,assessment_question_id"}).select("*").single();if(error)throw error;return maa(data);},
 async submitAttempt(id){const{data,error}=await supabase.from("learning_attempts").update({status:"submitted",submitted_at:new Date().toISOString()}).eq("id",id).select("*").single();if(error)throw error;return mat(data);}
};
