-- Legacy remote migration history marker.
-- Live Supabase already contains the effects of 20260909072359_enforce_product_permissions_rls.
-- Preserve the historical version without replaying legacy SQL.
