import type { Database, Json } from "@/core/database/database.types";
import { supabase } from "@/core/infrastructure/supabase/client";
import type { LearningGradebookCategory,LearningGradebookEntry,LearningTermGrade } from "../types/learning-gradebook.types";
type CategoryRow=Database["public"]["Tables"]["learning_gradebook_categories"]["Row"];
type EntryRow=Database["public"]["Tables"]["learning_gradebook_entries"]["Row"];
type TermGradeRow=Database["public"]["Tables"]["learning_term_grades"]["Row"];
const obj=(v:Json|null):Record<string,unknown>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};
const mc=(r:CategoryRow):LearningGradebookCategory=>({id:r.id,organizationId:r.organization_id,code:r.code,name:r.name,description:r.description,defaultWeight:r.default_weight,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at});
const me=(r:EntryRow):LearningGradebookEntry=>({id:r.id,tenantId:r.tenant_id,organizationId:r.organization_id,termId:r.term_id,classGroupId:r.class_group_id,classSubjectId:r.class_subject_id,studentUserId:r.student_user_id,categoryId:r.category_id,title:r.title,description:r.description,recordType:r.record_type as LearningGradebookEntry["recordType"],sourceType:r.source_type as LearningGradebookEntry["sourceType"],assignmentId:r.assignment_id,assessmentId:r.assessment_id,attemptId:r.attempt_id,assessmentResultId:r.assessment_result_id,topicId:r.topic_id,objectiveId:r.objective_id,score:r.score,maxScore:r.max_score,percentage:r.percentage,weight:r.weight,includedInGrade:r.included_in_grade,recordedAt:r.recorded_at,notes:obj(r.notes),createdBy:r.created_by,updatedBy:r.updated_by,createdAt:r.created_at,updatedAt:r.updated_at});
const mt=(r:TermGradeRow):LearningTermGrade=>({id:r.id,tenantId:r.tenant_id,organizationId:r.organization_id,termId:r.term_id,classGroupId:r.class_group_id,classSubjectId:r.class_subject_id,studentUserId:r.student_user_id,score:r.score,letterGrade:r.letter_grade,status:r.status as LearningTermGrade["status"],calculation:obj(r.calculation),finalizedAt:r.finalized_at,finalizedBy:r.finalized_by,notes:obj(r.notes),createdAt:r.created_at,updatedAt:r.updated_at});
export const learningGradebookRepository={
 async listCategories(organizationId:string){const{data,error}=await supabase.from("learning_gradebook_categories").select("*").eq("organization_id",organizationId).order("name");if(error)throw error;return(data??[]).map(mc);},
 async listEntries(input:{termId?:string;classSubjectId?:string;studentUserId?:string}){let q=supabase.from("learning_gradebook_entries").select("*").order("recorded_at",{ascending:false});if(input.termId)q=q.eq("term_id",input.termId);if(input.classSubjectId)q=q.eq("class_subject_id",input.classSubjectId);if(input.studentUserId)q=q.eq("student_user_id",input.studentUserId);const{data,error}=await q;if(error)throw error;return(data??[]).map(me);},
 async listTermGrades(input:{termId:string;classSubjectId?:string;studentUserId?:string}){let q=supabase.from("learning_term_grades").select("*").eq("term_id",input.termId).order("score",{ascending:false});if(input.classSubjectId)q=q.eq("class_subject_id",input.classSubjectId);if(input.studentUserId)q=q.eq("student_user_id",input.studentUserId);const{data,error}=await q;if(error)throw error;return(data??[]).map(mt);},
 async createCategory(input:{organizationId:string;code:string;name:string;description?:string|null;defaultWeight?:number}){const{data,error}=await supabase.from("learning_gradebook_categories").insert({organization_id:input.organizationId,code:input.code,name:input.name,description:input.description??null,default_weight:input.defaultWeight??1}).select("*").single();if(error)throw error;return mc(data);},
 async createEntry(input:Database["public"]["Tables"]["learning_gradebook_entries"]["Insert"]){const{data,error}=await supabase.from("learning_gradebook_entries").insert(input).select("*").single();if(error)throw error;return me(data);},
 async upsertTermGrade(input:Database["public"]["Tables"]["learning_term_grades"]["Insert"]){const{data,error}=await supabase.from("learning_term_grades").upsert(input,{onConflict:"term_id,class_subject_id,student_user_id"}).select("*").single();if(error)throw error;return mt(data);}
};