import type { Database, Json } from "@/core/database/database.types";
import { supabase } from "@/core/infrastructure/supabase/client";
type LearningGradebookAuditRow = { id: string; action: string; changed_at: string; reason: string | null };

import type { LearningGradebookCategory,LearningGradebookEntry,LearningTermGrade } from "../types/learning-gradebook.types";
type CategoryRow=Database["public"]["Tables"]["learning_gradebook_categories"]["Row"];
type EntryRow=Database["public"]["Tables"]["learning_gradebook_entries"]["Row"] & {status:string;comment:string|null;late:boolean};
type TermGradeRow=Database["public"]["Tables"]["learning_term_grades"]["Row"] & {override_score:number|null;override_grade:string|null;override_reason:string|null};
const obj=(v:Json|null):Record<string,unknown>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};
const mc=(r:CategoryRow):LearningGradebookCategory=>({id:r.id,organizationId:r.organization_id,code:r.code,name:r.name,description:r.description,defaultWeight:r.default_weight,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at});
const me=(r:EntryRow):LearningGradebookEntry=>({id:r.id,tenantId:r.tenant_id,organizationId:r.organization_id,termId:r.term_id,classGroupId:r.class_group_id,classSubjectId:r.class_subject_id,studentUserId:r.student_user_id,categoryId:r.category_id,title:r.title,description:r.description,recordType:r.record_type as LearningGradebookEntry["recordType"],sourceType:r.source_type as LearningGradebookEntry["sourceType"],assignmentId:r.assignment_id,assessmentId:r.assessment_id,attemptId:r.attempt_id,assessmentResultId:r.assessment_result_id,topicId:r.topic_id,objectiveId:r.objective_id,score:r.score,maxScore:r.max_score,percentage:r.percentage??(r.max_score>0?(r.score/r.max_score)*100:0),weight:r.weight,includedInGrade:r.included_in_grade,status:r.status as LearningGradebookEntry["status"],comment:r.comment,late:r.late,recordedAt:r.recorded_at,notes:obj(r.notes),createdBy:r.created_by,updatedBy:r.updated_by,createdAt:r.created_at,updatedAt:r.updated_at});
const mt=(r:TermGradeRow):LearningTermGrade=>({id:r.id,tenantId:r.tenant_id,organizationId:r.organization_id,termId:r.term_id,classGroupId:r.class_group_id,classSubjectId:r.class_subject_id,studentUserId:r.student_user_id,score:r.score,letterGrade:r.letter_grade,status:r.status as LearningTermGrade["status"],calculation:obj(r.calculation),overrideScore:r.override_score,overrideGrade:r.override_grade,overrideReason:r.override_reason,finalizedAt:r.finalized_at,finalizedBy:r.finalized_by,notes:obj(r.notes),createdAt:r.created_at,updatedAt:r.updated_at});
export const learningGradebookRepository={
 async listCategories(organizationId:string){const{data,error}=await supabase.from("learning_gradebook_categories").select("*").eq("organization_id",organizationId).order("name");if(error)throw error;return(data??[]).map(mc);},
 async listTerms(organizationId:string){const{data,error}=await supabase.from("learning_terms").select("id,organization_id,code,name,status,starts_on,ends_on").eq("organization_id",organizationId).order("starts_on",{ascending:false});if(error)throw error;return data??[];},
 async listEntries(input:{termId?:string;classSubjectId?:string;studentUserId?:string}){let q=supabase.from("learning_gradebook_entries").select("*").order("recorded_at",{ascending:false});if(input.termId)q=q.eq("term_id",input.termId);if(input.classSubjectId)q=q.eq("class_subject_id",input.classSubjectId);if(input.studentUserId)q=q.eq("student_user_id",input.studentUserId);const{data,error}=await q;if(error)throw error;return(data??[]).map(me);},
 async listTermGrades(input:{termId:string;classSubjectId?:string;studentUserId?:string}){let q=supabase.from("learning_term_grades").select("*").eq("term_id",input.termId).order("score",{ascending:false});if(input.classSubjectId)q=q.eq("class_subject_id",input.classSubjectId);if(input.studentUserId)q=q.eq("student_user_id",input.studentUserId);const{data,error}=await q;if(error)throw error;return(data??[]).map(mt);},
 async listTopics(topicIds:string[]){if(!topicIds.length)return[];const{data,error}=await supabase.from("learning_topics").select("id,code,name,sequence_no").in("id",topicIds).order("sequence_no");if(error)throw error;return data??[];},
 async createCategory(input:{organizationId:string;code:string;name:string;description?:string|null;defaultWeight?:number}){const{data,error}=await supabase.from("learning_gradebook_categories").insert({organization_id:input.organizationId,code:input.code,name:input.name,description:input.description??null,default_weight:input.defaultWeight??1}).select("*").single();if(error)throw error;return mc(data);},
 async updateCategory(input:{id:string;code:string;name:string;description?:string|null;defaultWeight:number;status:string}){const{data,error}=await supabase.from("learning_gradebook_categories").update({code:input.code,name:input.name,description:input.description??null,default_weight:input.defaultWeight,status:input.status}).eq("id",input.id).select("*").single();if(error)throw error;return mc(data);},
 async createEntry(input:Database["public"]["Tables"]["learning_gradebook_entries"]["Insert"]){const{data,error}=await supabase.from("learning_gradebook_entries").insert(input).select("*").single();if(error)throw error;return me(data as EntryRow);},
 async updateManualEntry(input:{entryId:string;title:string;score:number;maxScore:number;categoryId?:string|null;status:string;comment?:string|null;late?:boolean;reason?:string|null}){const{data,error}=await supabase.rpc("update_learning_manual_gradebook_entry" as never,{p_entry_id:input.entryId,p_title:input.title,p_score:input.score,p_max_score:input.maxScore,p_category_id:input.categoryId??null,p_status:input.status,p_comment:input.comment??null,p_late:input.late??false,p_reason:input.reason??null} as never);if(error)throw error;return data as string;},async setEntryIncludedInGrade(entryId:string,includedInGrade:boolean,updatedBy:string){
  const {data,error}=await supabase.from("learning_gradebook_entries").update({
    included_in_grade:includedInGrade,updated_by:updatedBy,
  }).eq("id",entryId).eq("source_type","manual").select("*").single();
  if(error)throw error;
  if(!data)throw new Error("The gradebook record could not be updated.");
  return me(data as EntryRow);
},
 async deleteManualEntry(entryId:string,reason?:string){const{data,error}=await supabase.rpc("delete_learning_manual_gradebook_entry" as never,{p_entry_id:entryId,p_reason:reason??null} as never);if(error)throw error;return Boolean(data);},
 async reopenTermGrade(input:{termId:string;classSubjectId:string;studentUserId:string;reason:string}){const{data,error}=await supabase.rpc("reopen_learning_term_grade" as never,{p_term_id:input.termId,p_class_subject_id:input.classSubjectId,p_student_user_id:input.studentUserId,p_reason:input.reason} as never);if(error)throw error;return data as string;},
 async overrideTermGrade(input:{termId:string;classSubjectId:string;studentUserId:string;score:number;grade:string;reason:string}){const{data,error}=await supabase.rpc("override_learning_term_grade" as never,{p_term_id:input.termId,p_class_subject_id:input.classSubjectId,p_student_user_id:input.studentUserId,p_override_score:input.score,p_override_grade:input.grade,p_reason:input.reason} as never);if(error)throw error;return data as string;},
 async listAudit(input:{termId?:string;classSubjectId?:string;studentUserId?:string}):Promise<LearningGradebookAuditRow[]>{let q=supabase.from("learning_gradebook_audit_log" as never).select("*").order("changed_at",{ascending:false});if(input.termId)q=q.eq("term_id",input.termId);if(input.classSubjectId)q=q.eq("class_subject_id",input.classSubjectId);if(input.studentUserId)q=q.eq("student_user_id",input.studentUserId);const{data,error}=await q;if(error)throw error;return (data??[]) as unknown as LearningGradebookAuditRow[];},
 async bulkImportEntries(input:{termId:string;classSubjectId:string;rows:Array<{studentUserId:string;title:string;score:number;maxScore:number;categoryId?:string|null}>}){const{data,error}=await supabase.rpc("create_learning_gradebook_bulk_entries" as never,{p_term_id:input.termId,p_class_subject_id:input.classSubjectId,p_rows:input.rows} as never);if(error)throw error;return Number(data);},
 async createManualEntry(input:{termId:string;classSubjectId:string;studentUserId:string;title:string;score:number;maxScore:number;categoryId?:string|null;description?:string|null}){const{data,error}=await supabase.rpc("create_learning_manual_gradebook_entry",{p_term_id:input.termId,p_class_subject_id:input.classSubjectId,p_student_user_id:input.studentUserId,p_title:input.title,p_score:input.score,p_max_score:input.maxScore,p_category_id:input.categoryId??undefined,p_description:input.description??undefined});if(error)throw error;return data;},
 async calculateTermGrade(input:{termId:string;classSubjectId:string;studentUserId:string}){const{data,error}=await supabase.rpc("calculate_learning_term_grade",{p_term_id:input.termId,p_class_subject_id:input.classSubjectId,p_student_user_id:input.studentUserId});if(error)throw error;return data;},
 async finalizeTermGrade(input:{termId:string;classSubjectId:string;studentUserId:string}){const{data,error}=await supabase.rpc("finalize_learning_term_grade",{p_term_id:input.termId,p_class_subject_id:input.classSubjectId,p_student_user_id:input.studentUserId});if(error)throw error;return data;}
};